### ISSUE TITLE
Add the WebGL spec(s) from https://www.khronos.org/registry/webgl/specs/latest/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#10]
Any overview of HTML5 standardization activities should include a link to the WebGL specs.

**Comment by dret** [comment]
#7 explains there general problem. and i am torn about linking to private company specs which seem to be entirely owned by them? any line you would draw between the more old-school open and public specs and company-backed and -hosted specs?

**Comment by sideshowbarker** [comment]
> i am torn about linking to private company specs which seem to be entirely owned by them? any line you would draw between the more old-school open and public specs and company-backed and -hosted specs

The WebGL spec is not a “company-backed“ or “company-hosted” spec any more than any W3C spec is. Khronos is non-profit consortium, with member companies that participate in it just like companies do in the W3C. And the WebGL spec was developed at Kronos with direct participation from multiple browser-engine implementers. That work was done at Kronos instead of at the W3C mostly just because it made the most sense to do there, given the fact that the spec basically just defines a set of thin bindings for the Web to the main technology developed in the Kronos consortium, OpenGL, which is itself also an open standard.

Anyway, regardless of all that and as I mentioned in a comment for another issue here, the fact is that the Web platform is agnostic as to where the features is contains happened to have been developed, and Web developers don’t care where the features were developed—they just care about those features they can use natively across different browsers. That’s the set of features they want to know about, and I think they’d appreciate having them all listed in one place (e.g., the overview here).

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/3684de34556190e4483297cc69b64fda6af2f98b addresses this issue. please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
looks superb
