### ISSUE TITLE
Reference Web Notifications from https://notifications.spec.whatwg.org/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#11]
The Web Notifications spec at https://notifications.spec.whatwg.org/ is in active development. Omitting any reference to it at all misleads users into thinking the (essentially frozen) W3C Web Notifications spec represents the latest development for Notifications.

I think it’d be fine to list both versions, with some kind of note indicating what each represents (e.g., the W3C spec represents what’s already been implemented and shipped in some browsers, while the other spec represents the latest consensus on what the API should be going forward.)

**Comment by dret** [comment]
#7 explains the general problem. in the current format, it might be hard to add notes and somehow indicate relationships between specs. any suggestion on how this could be presented in a simple way? and once again, i'd like to stay out of the political issues here and simply present what's currently been worked on by the W3C.

**Comment by sideshowbarker** [comment]
As I mentioned in a comment for the issue I raised about the Fullscreen spec, I think it would be sufficient just to have an additional section titled **Specifications Elsewhere** or something, and to list the https://notifications.spec.whatwg.org/ spec there. Beyond that I think it’d be preferable to also have some kind of footnote/annotation in both places to explain the relationship, but I don’t think that’s essential. But I do think that minimally, the https://notifications.spec.whatwg.org needs to be included.

**Comment by dret** [comment]
i'll add it because like you said, it may be useful to have it listed here. but what i find confusing is that both seem to do the same thing, under a different name. well, i guess this is just another case of the current W3C/WHATWG clash, my hope is that at some point they'll figure out a more productive strategy than what they're currently doing. https://github.com/dret/HTML5-overview/commit/b01cefd0f12ceb6da548ce16f269e0f3294e17b0 addresses your issue, as usual please check and close. thanks for all your suggestions, keep them coming!

**Comment by sideshowbarker** [comment]
thanks

And yeah I hope we can find ways to eliminate confusion around this spec but in the long term as the current Notifications spec moves further along and gets implementations, at that time the current confusion will just somewhat naturally dissipate by recognizing that the Notifications rec will have passed into the same sort of state of (ir)relevance that the old DOM specs have, and therefore there will be no more need to include the Notifications Rec in this overview—any more than there's a need to include the HTML4 spec in it.

P.S. Some people have suggested the only reason we’ll be publishing the old Notifications spec as Rec at all at this time (instead of retiring it to Note) is to get royalty-free protection against essential claims in any existing patents that the spec might be construed as infringing on. But that’s not the only reason (though I can understand why some people might think it is).
