### ISSUE TITLE
Add the Web NFC API http://w3c.github.io/web-nfc/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#13]
The Web NFC API is a CG spec, not a WG spec, but it’s included in http://www.w3.org/2015/05/mobile-web-app-state/ so it makes some sense to add it to this overview also.

**Comment by dret** [comment]
#7 explains the general problem. this one is a bit different because it's W3C-hosted, but not the same kind of track than the more official W3C TRs. i do agree that this one would be useful, but again, how would you make clear (if at all) that this is not at the same level than the TR specs?

**Comment by sideshowbarker** [comment]
For CG specs, I suggest just adding a new section titled **Community Group Specifications** or **Community Group Drafts**. That seems like the simplest way to handle it.

**Comment by dret** [comment]
would those typically also have or need two links (like the "stable TR" link and the optional "ED" link), and would those follow the same logic?

**Comment by sideshowbarker** [comment]
> would those typically also have or need two links (like the "stable TR" link and the optional "ED" link), and would those follow the same logic?

Just one link. There's only a single version of them (a la the living-spec model).

If/when they moved into a WG and get published as WDs they'd graduate out to the other sections.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/7117541535183ee64ab066e7f62cae28f97c5378 should address this issue. please check and close issue if that's the case.

**Comment by sideshowbarker** [comment]
yup
