### ISSUE TITLE
Add the Web Bluetooth spec http://w3c.github.io/web-nfc/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#14]
The Web Bluetooth spec is a CG spec, not a WG spec, but it’s included in http://www.w3.org/2015/05/mobile-web-app-state/ so it makes some sense to add it to this overview also.

**Comment by dret** [comment]
please see #13, same questions here.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/7117541535183ee64ab066e7f62cae28f97c5378 should address this issue. please check and close issue if that's the case.

**Comment by sideshowbarker** [comment]
roger that
