### ISSUE TITLE
Add the Web Speech API https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#15]
The Web Speech API spec is a CG spec, not a WG spec, but it’s included in http://www.w3.org/2015/05/mobile-web-app-state/ so it makes some sense to add it to this overview also.

**Comment by dret** [comment]
please see #13 and #14, same questions here.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/0d81954e33521ea192d8f847ef67b18608e31e51 addresses this issue; please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
Looks good
