### ISSUE TITLE
Add the Generic Sensor API https://github.com/w3c/sensors#sensor-api-unification-sketch

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#16]
The Generic Sensor API is a deliverable in the Device APIs WG, currently just a sketch at https://github.com/w3c/sensors#sensor-api-unification-sketch but perhaps worth adding a section titled **Early Work to Keep an Eye On** or **Incubation Stage** or **On the Horizon** something like that? (And maybe not including it in the counts published about number of specs in progress.)

Despite the lack of even an ED at this point, there's been some real work going on and I think it has a good chance of maturing into something that actually gets implemented and becomes part of the platform. Not at all a sure thing of course, but for a few more details and history, see http://www.w3.org/2015/05/14-dap-minutes.html#item07 and https://lists.w3.org/Archives/Public/public-device-apis/2015May/0039.html and https://lists.w3.org/Archives/Public/public-device-apis/2014Nov/0018.html

**Comment by dret** [comment]
i like the idea of a "work in progress" section. would it be best to add this as a third section after "W3C TR Specs" and "Other Specs"? any other candidates for this section? generally speaking, this might get close to the limit of what works well in a single MD page, but that's a different issue, i guess.

**Comment by sideshowbarker** [comment]
> any other candidates for this section?

https://storage.spec.whatwg.org/ is another recent development that I think is at a similar level of (im)maturity but that I think also has promise at a similar level

**Comment by dret** [comment]
thanks, i'll add that one as well. but actually, that one seems to be an actual draft (like https://github.com/dret/HTML5-overview/commit/6a7d972383cff1bc1ad79198c7b7b853a09503b9, which is not official but looks like a good starting point) and not just an early sketch like the generic sensor API.

**Comment by sideshowbarker** [comment]
> > https://storage.spec.whatwg.org/ is another recent development that I think is at a similar level of (im)maturity but that I think also has promise at a similar level

> actually, that one seems to be an actual draft (like 6a7d972, which is not official but looks like a good starting point) and not just an early sketch like the generic sensor API

That Storage spec is not really implemented as such anywhere yet. That's why I think it's more of just an exploratory thing at this point.

BTW about the generic sensor API, there is now a formatted draft of that at https://w3c.github.io/sensors/ Its content at this point is mostly just placeholder notes to corresponding issues but at least it's some actual content at a stable URL that resources like this overview can point to, anticipating the content will get updated as the work matures.

**Comment by dret** [comment]
thanks to @tobie now there is an ED, and https://github.com/dret/HTML5-overview/commit/d022971aa163112d84d1d7c3e17a8da856011a83 should address your issue. please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
rock and roll
