### ISSUE TITLE
add HTML Accessibility API Mappings 1.0 

### ISSUE THREAD

**Issue by stevefaulkner** [dret/HTML5-overview#17]
this work is part of HTML http://www.w3.org/TR/html-aam-1.0/
HTML Accessibility API Mappings (HTML-AAM) defines how user agents map HTML 5.1 [HTML51] elements and attributes to platform accessibility application programming interfaces (APIs). It leverages and extends the Core Accessibility API Mappings 1.1 [CORE-AAM] and the Accessible Name and Description: Computation and API Mappings 1.1 [ACCNAME-AAM] for use with the HTML 5.1 host language. Documenting these mappings promotes interoperable exposure of roles, states, properties, and events implemented by accessibility APIs and helps to ensure that this information appears in a manner consistent with author intent.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/3a169d88ecf80056387b49c2c2a2622152abf57f addresses this issue; please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
Great to see this added. @stevefaulkner I reckon you can close this…
