### ISSUE TITLE
add ARIA in HTML

### ISSUE THREAD

**Issue by stevefaulkner** [dret/HTML5-overview#18]
http://www.w3.org/TR/html-aria/
This specification defines the web developer rules (author conformance requirements) for the use of [wai-aria-1.1] attributes on [HTML51] elements. It also defines requirements for Conformance Checking tools.

**Comment by dret** [comment]
maybe this is a duplicate of #12?

**Comment by sideshowbarker** [comment]
> maybe this is a duplicate of #12?

http://www.w3.org/TR/html-aria/ is a separate spec from the ARIA spec; it's a [Rec-track chartered deliverable of its own](http://www.w3.org/2013/09/html-charter.html#deliverables) in the HTML WG and defines normative document-conformance requirements for ARIA in HTML specifically—whereas the ARIA spec itself defines general language-neutral requirements for all “host languages” that might incorporate ARIA attributes into their specs.

So IHMO the ARIA in HTML spec should definitely be included in the **Working Drafts** of this overview.

**Comment by dret** [comment]
is https://github.com/dret/HTML5-overview/commit/9ca181076da431aa08e203d56f427476832d7380 sufficient to make everybody happy? if so, please close issue. thx!

**Comment by dret** [comment]
assuming the fix was good enough, closing this issue.
