### ISSUE TITLE
Remove the Notes section and all specs in it

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#19]
I believe it’s not actually helpful for this overview to include any specs that have been abandoned by a W3C WG—especially not specs for which there are either no current implementations or that have no probability of ever being implemented across multiple UAs in such a way that anybody can say they will have become part of the Web Platform.

Concretely that would mean the entire **Notes** section should be dropped from this overview, because it includes only specs that have for whatever reasons been formally abandoned by W3C WGs.

I can see the **Notes** section being over historical interest, but as far as I understand the scope of this overview, the overview is not intended to provide a historical record (otherwise there's actually a whole lot of other specs it ought to include) but instead to capture the current state of development of “HTML5“ as a programming platform, reflected by the set of technologies for which there are either relevant specs which are still active progressing, or that have versions that have become W3C Recommendations.

So I think the **Notes** section could better be moved out to become a separate document, titled `retired.md` or some such (if it’s kept at all).

**Comment by dret** [comment]
so i guess https://github.com/dret/HTML5-overview/commit/7716a82a66100cda1e0bc84fe687825a5b336995 is not enough to make you happy? if not, then i'll think about creating a separate page. i still think it's nice to have that set available somewhere.

**Comment by sideshowbarker** [comment]
I think https://github.com/dret/HTML5-overview/commit/7716a82a66100cda1e0bc84fe687825a5b336995 helps some but I’d guess it’s also going to cause people to next wonder which particular specs in the Notes section are abandoned vs which are just outdated but still being worked on elsewhere. I guess that could be clarified by an annotation for each spec but IMHO that would just be added complexity without any benefit to most users.

I’ve been assuming that the main intended users of this overview are Web developers who want at list of all APIs that are under development related to browsers as a programming platform, with some indication of what level of maturity the specs are at. And I think this overview does that well. The specs that are in development are all specs that I can imagine Web developers actually wanting to take some time to read themselves so that they can learn more about what features are available to use.

But as far as the specs in the Notes section, nothing published at the W3C as a Note is under development at the W3C any longer. Instead they are all by definition things for which all development at the W3C has stopped. And there’s no use case I can imagine in which a Web developer would want to actually take time to read any of those Note specs.

So while I can imagine that there might be some users of the overview with curiosity about specs that had been in development at the W3C at one time but are not any longer, I think most Web developers at least don’t care much at all to know that and don’t want to read any of those specs.

Instead I would think what they’d prefer is just a list of those specs that are actually still relevant to programming Web applications that run in browsers.

This gets back to what I wrote in https://github.com/dret/HTML5-overview/issues/20#issuecomment-114078037 when I said that I think the value of this overview is that it’s curated, instead of just being a dump of a bunch of specs that W3C working groups have published but that may or may not actually be relevant. The value of the overview is that it restricts itself just to telling users which specs are actually relevant currently.

**Comment by dret** [comment]
next try: does https://github.com/dret/HTML5-overview/commit/0715a0fdb288c81f90061ebb4fcb1574ab04812f make you sufficiently happy? any specific suggestions for improvements highly welcome!

**Comment by sideshowbarker** [comment]
Yes, thanks much for making this change.
