### ISSUE TITLE
Remove the Web NFC API http://www.w3.org/TR/nfc/ version from Working Drafts section

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#21]
I should have thought to mention this when I raised issue #13 but in the specific case of the Web NFC API, the existence of the CG spec at http://w3c.github.io/web-nfc/ by design completely obviates and supersedes the http://www.w3.org/TR/nfc/ WD version.

For background, see https://lists.w3.org/Archives/Public/public-nfc/2015Mar/0020.html and https://lists.w3.org/Archives/Public/public-nfc/2015Apr/0005.html

As those messages indicate, the NFC WG has been closed, and the intent was for the WG draft of the API to be moved to Note when the group closed. For whatever reason, that hasn’t happened yet (and I’ve started a W3C team-internal discussion to get it done now) but regardless it’s clear that draft has been abandoned by the WG that created it, so it can be safely removed from this overview.

I don’t think it’s necessary to wait for it to be formally moved to Note, because as I outlined in issue #19 IMHO this overview should not include a **Notes** section anyway.

**Comment by dret** [comment]
this one was just moved to NOTE status: https://github.com/dret/HTML5-overview/commit/3a846389a31c43a4f8cc148f46db3464ef189b74
