### ISSUE TITLE
Remove the “Audio Processing API” document http://www.w3.org/TR/audioproc/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#22]
Despite the “Audio Processing API” title of the WD at http://www.w3.org/TR/audioproc/ that document does not actually itself define any API, nor does it normatively define anything at all. Instead it simply references two other documents:
* a WD for the current Web Audio API at http://www.w3.org/TR/webaudio/ that is implemented in multiple UAs and is still a Rec-track deliverable of the Audio WG
* a Note for the old MediaStream Processing API proposal from Mozilla which never ended up becoming a deliverable of the Audio WG nor any other WG, and was never implemented in any UA except Firefox

Given all that and the fact that this overview already lists the Web Audio API, I think that listing of the Web Audio API is sufficient, and it’s not necessary or useful for this overview to also list the “Audio Processing API” document.

**Comment by dret** [comment]
surprisingly, this one is still an official W3C WD. would it address your issue to move it to the list of abandoned specs? https://github.com/dret/HTML5-overview/blob/master/MD/abandoned.md

**Comment by sideshowbarker** [comment]
> surprisingly, this one is still an official W3C WD. would it address your issue to move it to the list of abandoned specs?

Yeah. I’m certain the WG doesn’t plan to do anything further with it. It’s an artifact of earlier disagreement in the group, and should probably have been published as a Note to begin with. Regardless, the group rightly should have since already moved it to a Note, and I wlll take the time to bring that up for discussion with the W3Cteam contacts for the group.

**Comment by dret** [comment]
great, thanks! i guess i'll just wait for this WD to officially change status, then.

**Comment by dret** [comment]
any chance this will actually happen, or is http://www.w3.org/TR/audioproc/ in eternal WD limbo?

**Comment by sideshowbarker** [comment]
Closing this as I don’t actually care enough to chase after the Audio WG about it.

**Comment by dret** [comment]
On 2016-08-23 18:48, Michael[tm] Smith wrote:

> Closing this as I don’t actually care enough to chase after the Audio WG
> about it.

too bad but understood. too bad w3c doesn't have enough housekeeping in 
place to make sure the spec stream stays in a well-defined state.
