### ISSUE TITLE
Remove Task Scheduler, App Lifecycle, TCP UDP Sockets, App URI

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#23]
The System Applications WG is no longer functioning as a WG (see related details in issue #20) and per items 6 to 9 in https://lists.w3.org/Archives/Public/public-sysapps/2015Apr/0017.html and  https://lists.w3.org/Archives/Public/public-sysapps/2015Apr/0029.html the group has abandoned all work on the Task Scheduler, App Lifecycle, TCP UDP Sockets, App URI specs and it’s not clear that any other WG will pick up work on those specs, nor even that they would fit in any other group.

Rightly the SysApps WG should have already moved all those specs to Note, but they have not yet, and since the WG is not actually functioning any longer, they will not be moving them to Note any time soon.

So given all that aand the fact that none of those specs actually have any implementations, IMHO the right thing to do for now would be to remove all of them from this overview (lest people reading the overview be misled into thinking any of those specs are actually still progressing anywhere).

**Comment by dret** [comment]
task scheduler: https://github.com/dret/HTML5-overview/commit/1b8436396a40190310d3dfa6b8096c441a00fb78
app: URL: https://github.com/dret/HTML5-overview/commit/da934ae3ddc18cea36244acbc5e37abe6a7f117a
TCP/UDP: https://github.com/dret/HTML5-overview/commit/f8918bf67617f25c3ee05be2f484bebb99b86da3
the lifecycle spec was never in the HTML5 list, i think, afaict, since it never made it to FPWD. i think these fixes resolve this issue, and if so, please close. thanks!

**Comment by dret** [comment]
added lifecycle for completeness https://github.com/dret/HTML5-overview/commit/b14b2f93d110369077a5d434230c0c7b6750bfc7, but it now shows up as "other" since it is not an official W3C NOTE. maybe not quite what you were looking for, @sideshowbarker?

**Comment by sideshowbarker** [comment]
> added lifecycle for completeness b14b2f9, but it now shows up as "other" since it is not an official W3C NOTE. maybe not quite what you were looking for, @sideshowbarker?

Well, I personally wouldn't include that spec, since it's not been updated in more than a year, doesn't seem to have any implementor support, and at this point has no home in any W3C WGs nor anywhere.
 
But I won't object to it being included if you want to. At least it's in scope as far as being intended for implementation in the Web runtime and the Web security model (as opposed to the other SysApp WG drafts, which were intended for a hypothetical off-Web runtime/security-model that never materialized).

Still I think that lifecycle spec has near-zero chance of ever getting implemented across UAs (or probably any UAs), and so near-zero chance of every becoming part of the Web platform.

**Comment by sideshowbarker** [comment]
Closing this since the specs in question have now been removed from the overview and I opened #27 about dropping Application Lifecycle and Events.
