### ISSUE TITLE
A few updates for WebApps' specs

### ISSUE THREAD

**Issue by AFBarstow** [dret/HTML5-overview#25]
* CORS is a Recommendation
* Selectors API Level 1 is a Recommendation
* Selectors API Level 2 was last published as a WG Note so it should be moved to the Notes section
* XHR Level 2 was last published as a WG Note so it should be moved to the Notes section

**Comment by dret** [comment]
CORS: https://github.com/dret/HTML5-overview/commit/465bcd28ea0f9f38c66a0679f876204e5aefd30a (thanks for spotting this one!)

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/b11c54c92809007071aa5f1a9103ba70cc511bf7 is another fix, thanks for spotting that one as well!

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/ecc0a4418afa58e424af948028498430a3ae3e85, yet another one, and thanks again.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/3de85408074bc795c5fdc4810a811d2c8028f8cd is the last one, thanks for all the updates!
