### ISSUE TITLE
Add MathML?

### ISSUE THREAD

**Issue by dret** [dret/HTML5-overview#28]
@iherman made a point #26 about adding MathML. if so, why would it be HTML5 specifically, and not just some king of content type that modern browsers should support (just like PNG)?

**Comment by dginev** [comment]
Hi! I am not sure what this repository's goal is exactly, but I am following up on your Twitter question here:
https://twitter.com/dret/status/644201896069062656

What I know is that MathML has been part of the HTML5 proposals for some time now, and you can see the (I think latest) details here in the nightly HTML5 draft:
http://www.w3.org/html/wg/drafts/html/master/semantics.html#mathml

Also, to clarify the role of the MathML Association - we are not part of the standardization process of either HTML5 or MathML. The association's role comes as a consequence to the two standards uniting, and we want to encourage adoption and awareness of MathML. So by all means, if you are doing HTML5 reporting/publicity, do include MathML - math matters :)

**Comment by dret** [comment]
thanks for the response. does https://github.com/dret/HTML5-overview/commit/e5f3fb5744d6f61d5dd29e840729efa26e254814 look good enough, or should specs be added as well?

**Comment by dginev** [comment]
Looks great to me, thanks for adding it.

**Comment by dret** [comment]
thanks for helping out, and closing the issue.
