### ISSUE TITLE
html5 spec

### ISSUE THREAD

**Issue by bmvakili** [dret/HTML5-overview#4]
To be complete, why not add this one too?
http://www.w3.org/TR/html5/

**Comment by dret** [comment]
that's of course a good point, but it is a different animal, isn't it? would you just add it in the very same way as all the others?

**Comment by bmvakili** [comment]
I'd say it's the heart of the animal; so while got the toes there, might add heart too.
Yes, the same as as the other items there; It could be an item in the first part; bumps Recommendations count to 13.

**Comment by dret** [comment]
thanks for the suggestion, and https://github.com/dret/HTML5-overview/commit/59ae4bd88f606248ba324afac51bab1740640205 should address it.
