### ISSUE TITLE
Add the DOM spec https://dom.spec.whatwg.org/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#6]
It’s odd to have an “overview of all HTML5 standardization activities“ that doesn’t include a DOM spec.

**Comment by dret** [comment]
you're of course technically right, but then again, there are many DOM specs and so far maybe i was just a bit concerned if that wouldn't be too confusing. maybe that's where one flat list really starts to become a bit too simple.
http://www.w3.org/standards/techs/dom might be a useful starting point. would you add just DOM core, or this bigger set? and would you expect those specs to simply show up like the other specs?

**Comment by sideshowbarker** [comment]
> there are many DOM specs

There aren’t, actually. At least not many that aren’t obsolete. Instead, there’s really only two current specs for the DOM: the actual DOM spec itself (which obsoletes all previous DOM specs while also specifying DOM features implemented in browsers which have never been specified in any previous DOM specs), along with the DOM Parsing and Serialization spec. 

> http://www.w3.org/standards/techs/dom might be a useful starting point. would you add just DOM core, or this bigger set?

None of the “Document Object Model (DOM) Level*..“ specs from that page should be included in anything that claims to be providing current information. Those are all legacy obsolete specs. And as far the other specs listed there like the Server-Sent Events spec, that's no more a spec for the DOM than the Web Sockets spec is a spec for the DOM.

So since the only DOM specs that should be listed are the DOM spec itself and the DOM Parsing and Serialization spec, and the overview already includes the DOM Parsing and Serialization spec, then I think the only spec that would need adding in order to resolve this issue is https://dom.spec.whatwg.org/

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/87fa127e029dc50ff0d2dcc7155fc7528226d858 addresses this issue.
