### ISSUE TITLE
Add the Fetch spec https://fetch.spec.whatwg.org/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#7]
The Fetch spec is very much part of “HTML5 standardization activities” as far as the scope of that is outlined in the intro to the docs here. Yeah, it’s not a spec in any W3C working group, but the intro here doesn’t say the scope of this overview is limited only to specs being developed in W3C working groups.

**Comment by dret** [comment]
you're right, but so far it has been limited to W3C specs only, and because of this, there's a bit of code in there that assumes that TR names follow the W3C pattern. that code would need to be changed to allow non-W3C specs. is there any line you would draw, though? i think i would at least still want to mark and distinguish the more official W3C-track documents, and then the others that may float around.

**Comment by sideshowbarker** [comment]
> is there any line you would draw, though?

Given that the stated scope is to provide an “overview of all HTML5 standardization activities… where all the APIs under development are listed” than that’s what I think it should be. It seems to me that already draws the line pretty clearly. The platform is agnostic as to what SDO a particular native technology/feature may have been developed. I mean, obviously there’s no mechanism in the platform where it examines whether a particular standard feature is provided by a spec developed at the W3C.

Because of that, IMHO it’s not useful to limit any information provided to Web developers to only being information about W3C technologies. Web developers couldn’t care less where the programming features of the platform happened to have been developed; instead they just want to know what the set of available features are.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/d61bda21b8c9094d0c86b4120e16e33c10b4088a adds the Fetch spec, XSLT (and thus MD) update is in the works.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/eb74c676312b5a381bcea4fabe26aac6b0f385f0 adds non-W3C TR specs to list, please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
> eb74c67 adds non-W3C TR specs to list, please check and close issue if it's good enough.

Thanks again
