### ISSUE TITLE
Prefer references to EDs and others spec versions that are in active development

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#8]
A lot of the spec spec links in this overview are to outdated TR drafts. But those TR versions are almost always not the most helpful versions for users. Instead users should typically be reading and using the latest editor’s drafts.

I understand the rationale for classifying the specs that have W3C versions maintained by W3C WGs into Rec/CR/WD/Note and I agree there’s real value in providing that information and I think that should be kept. But from that it does not necessarily follow that the spec links should be to the TR versions—or even to the W3C versions, if there's a more up-to-date version elsewhere.

**Comment by dret** [comment]
i am torn about this one. i am not a big fan of the current "living spec/document" fashion, but i do see that this is happening, and that the more formal distinction TR vs. editor's draft is a similar thing. would you like to see links to both? so far, i simply trust the W3C to make the latest and greatest official version available at the generic URI, and i don't specifically link to a version. any concrete proposal how to change this without creating too much noise, or making it necessary to update the links too often?

**Comment by sideshowbarker** [comment]
> TR vs. editor's draft is a similar thing. would you like to see links to both?
> any concrete proposal how to change this without creating too much noise

You can take a look http://www.w3.org/TR/#tr_Javascript_APIs to see how we handle it in the similar information we provide at www.w3.org site. For each spec we provide just two links: one to a TR URL and one to a ED URL.

However, I think the way we do it there is still less completely ideal, because for the TR link, it provides dated URLs instead of just the http://www.w3.org/TR/<shortname>/ URLs.

> or making it necessary to update the links too often?

I think if you were to just use the http://www.w3.org/TR/<shortname>/ URLs and the ED URLs, you would basically never need to ever update the links, since those are stable unchanging URLs (to documents that may change).

**Comment by dret** [comment]
> I think if you were to just use the http://www.w3.org/TR// URLs and the ED URLs, you would basically never need to ever update the links, since those are stable unchanging URLs (to documents that may change).

that sounds reasonable, as long as the EDs have generic URIs (which i think they almost always have). i'll try to add that to the code that's processing the XML asap, please stay tuned. it may take some community effort after that to actually add those ED URIs were they exist (hint, hint ;-).

**Comment by sideshowbarker** [comment]
> it may take some community effort after that to actually add those ED URIs were they exist (hint, hint ;-).

Sure, no rush and I'm happy to help when needed.

**Comment by dret** [comment]
please have a look at https://github.com/dret/HTML5-overview/commit/31b6ef87da278ac5d87b359755042778e5ae41ca (XML only) and let me know if something as simple as this could be good enough to address this issue.

**Comment by sideshowbarker** [comment]
> please have a look at 31b6ef8 (XML only) and let me know if something as simple as this could be good enough to address this issue.

Yeah as I said I the comment there, I think that'd be perfect.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/7aacb9676091c9ae2ed2f0beb2b6be2f9759b64d is a first attempt (currently only the geofencing WD has such an ED link), please let me know what you think.

**Comment by dret** [comment]
assuming that the simple link is sufficient, and closing this issue.

**Comment by sideshowbarker** [comment]
> 7aacb96 is a first attempt (currently only the geofencing WD has such an ED link), please let me know what you think.

Yeah, looks great—thanks
