### ISSUE TITLE
Reference the Fullscreen spec at https://fullscreen.spec.whatwg.org/

### ISSUE THREAD

**Issue by sideshowbarker** [dret/HTML5-overview#9]
The Fullscreen spec is alive and actively maintained at https://fullscreen.spec.whatwg.org/ but this overviewjust  lists the spec as W3C Note, which indicates that  W3C work on it has stopped and it’s no longer being actively maintained.

I think presenting the information about the Fullscreen spec that way is misleading to users. It essentially causes them to think the Fullscreen spec is dead.

**Comment by dret** [comment]
see #7 for the general issue. so far, all i do and can reference are W3C specs. from that perspective, fullscreen indeed is dead. if possible, i'd like to stay out of the politics of all of that, would you have a proposal how to handle these situations where the W3C work has stalled/stopped, but it is being continued elsewhere?

**Comment by sideshowbarker** [comment]
> would you have a proposal how to handle these situations where the W3C work has stalled/stopped, but it is being continued elsewhere?

I think for Fullscreen and Fetch and WebGL and other specs being developed outside of the W3C, you could just add a new section titled **Other Specifications** or **Non-W3C Specifications** or **Specifications Elsewhere** or something.

And for the case of Fullscreen or whatever other specs like it which have a version at the W3C that’s been retired but for which there’s an actively maintained spec elsewhere, if it’s feasible in your source markup to annotate it with a note pointing to the current version, you could just do that; but if it’s not feasible (or you don’t think it’s worth changing your tools to do it), then I don’t think it’s all that necessary as long at there is some section that does contain the maintained version so readers can find it.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/7b5f22ff530c9e5b33504d03f5325a0a0070c1ed addresses the issue, XSLT (and thus MD) is in the works.

**Comment by dret** [comment]
https://github.com/dret/HTML5-overview/commit/eb74c676312b5a381bcea4fabe26aac6b0f385f0 adds non-W3C TR specs to list, please check and close issue if it's good enough.

**Comment by sideshowbarker** [comment]
> eb74c67 adds non-W3C TR specs to list, please check and close issue if it's good enough.

Yup, thanks
